#!/bin/sh
# rezip-house.sh — timestamped .7z backup of the house source tree.
# Excludes:
#   - .git (GitHub is the history backup)
#   - disposable generated data (framebuffers, ascii-frame mirror, logs) —
#     same policy as
#     x0.parent-level-dev-env-04.04/yz.muchiverse/44.xyz.01.00/#.desktop/tidy-runtime.sh
#   - LIVE append-only files that running house processes (pals, taskbar,
#     ledgers, relays) write continuously — archiving one mid-write gives
#     a torn copy and makes 7z exit with a warning. These are pure
#     runtime state, never source.
#   - COMPILED ARTIFACTS (*.+x Linux binaries, *.exe Windows binaries,
#     *.o/*.a) — every one is regenerated by the house build_*.sh /
#     build.ps1 scripts; ~85 MB combined, never source. Vendored *.dll
#     redistributables are KEPT (small, not built from house source).
#   - #.NNEST_ASSETS/ — ~228 MB of VENDORED third-party asset packs
#     (mineclonia mob/item textures, cdda-tilesets/UltimateCataclysm).
#     Not house source, not in git, re-fetchable from their upstream
#     projects. Keep one separate full copy of this dir if you care
#     about the exact snapshot; the house .7z is for house source.
#   - *.mp3 — all 11 are tracked in git (GitHub has them); the two big
#     #.ref reference tracks are ~15 MB of the old archive.
#   (Added 2026-09-08 — the #.NNEST_ASSETS + *.exe + *.mp3 exclusions,
#    plus -mx=5, drop the archive ~60 MB -> ~29 MB. In-house image
#    assets — the ~321 PNGs OUTSIDE #.NNEST_ASSETS — and all *.csv
#    sprite data are KEPT.)
# Keeps only the newest house .7z - but ONLY after the new one is built and
# checked (2026-10-05 incident: this script used to delete the previous good
# archive FIRST, so running it on a wiped working tree replaced a good 34 MB
# backup with a 1 KB one).
#
# USAGE:
#   sh rezip-house.sh                full copy (DEFAULT, owner 2026-10-05): the whole
#                                    working tree INCLUDING compiled programs (*.+x
#                                    *.exe *.o *.a *.so) and *.mp3, so a restore
#                                    needs no rebuild. Still excludes .git (GitHub /
#                                    a `git bundle` is the history backup) and the
#                                    vendored #.NNEST_ASSETS.
#   sh rezip-house.sh --source-only  the old policy above: no compiled programs.
# SAFETY: refuses to run if more than 100 tracked files are missing from the
# working tree (it would archive a wipe), and refuses to replace the previous
# archive with one that has fewer than 1000 entries.
set -e
cd "$(dirname "$0")"
SRC="x0.parent-level-dev-env-04.04"
OUT="${SRC}_$(date +%Y%m%d-%H%M%S).7z"
OUTP="${OUT%.7z}.partial.7z"
FULL=1
[ "${1:-}" = "--source-only" ] && FULL=0

# pieces/sessions/ are tracked engine run copies that the engine deletes whenever
# a pc-hq window closes - routinely "missing", not a sign of a wipe.
MISSING=$(git ls-files --deleted 2>/dev/null | grep -v '/pieces/sessions/' | wc -l)
if [ "$MISSING" -gt 100 ]; then
    echo "rezip-house.sh: REFUSING - $MISSING tracked files are missing from the working tree (wiped?). Existing archives left untouched. Restore first: git ls-files -z --deleted | xargs -0 -n 4000 git checkout --" >&2
    exit 1
fi

# REAL FIX 2026-09-24, direct live report ("ERROR: stat error for
# .../livedesk_open.txt.tmp (No such file or directory)"): every open
# entity window (khtpm_entity.c) atomic-writes livedesk_open.txt via a
# write-then-rename through a .tmp scratch file - excluded above
# (*.tmp), but 7z 16.02 still stat()s an entry during its directory-
# scan pass BEFORE applying the exclude filter, so a .tmp file that
# gets renamed away in the gap between scan and stat (routine on a
# live house, worse right after a session restart's write burst) makes
# 7z hard-fail instead of silently skipping it - not a torn-copy risk
# (the excluded file was never going in the archive either way), just
# a spurious exit. One retry is a real, sufficient fix: the same race
# hitting twice in a row on two different files is not realistic.
zip_once() {
    if [ "$FULL" = 1 ]; then set --; else set -- -xr'!*.+x' -xr'!*.exe' -xr'!*.o' -xr'!*.a' -xr'!*.so' -xr'!*.mp3'; fi
    7z a -t7z -mx=5 "$OUTP" "$SRC" "$@" \
        -xr'!.git' \
        -xr'!#.NNEST_ASSETS' \
        -xr'!*.raw' -xr'!*.rgba32' \
        -xr'!ascii_frames' \
        -xr'!*.log' -xr'!*frame_history.txt' -xr'!gl_cli_out.txt' \
        -xr'!node_modules' \
        -xr'!history.txt' \
        -xr'!entity_menu_history' -xr'!entity_menu_frame_*.txt' \
        -xr'!strip_history.txt' -xr'!strip_ascii_pulse.txt' -xr'!strip_frame_changed.txt' \
        -xr'!*.pulse.txt' -xr'!renderer_pulse.txt' -xr'!*_changed.txt' \
        -xr'!*_ledger.txt' -xr'!pending_tx.txt' \
        -xr'!*.seq' \
        -xr'!*.frame.txt' \
        -xr'!*.tmp'
}
if ! zip_once; then
    echo "rezip-house.sh: first pass hit a live-file race, retrying once..." >&2
    rm -f "$OUTP"
    zip_once
fi
N=$(7z l -ba "$OUTP" 2>/dev/null | wc -l)
if [ "$N" -lt 1000 ]; then
    echo "rezip-house.sh: new archive has only $N entries - REFUSING to replace the previous archive. Kept: $OUTP" >&2
    exit 1
fi
mv "$OUTP" "$OUT"
for old in ${SRC}_*.7z; do [ "$old" = "$OUT" ] || rm -f "$old"; done
echo "OK $OUT ($N entries$([ "$FULL" = 1 ] && echo ', full: compiled programs included'), $(du -h "$OUT" | cut -f1))"
