#!/bin/sh
# rezip-house.sh — timestamped .7z backup of the house source tree.
# Excludes:
#   - .git (GitHub is the history backup)
#   - disposable generated data (framebuffers, ascii-frame mirror, logs) —
#     same policy as
#     x0.parent-level-dev-env-04.04/yz.muchiverse/44.xyz.01.00/#.desktop/tidy-runtime.sh
#   - LIVE append-only files that running house processes (pals, taskbar,
#     ledgers, relays) write continuously — archiving one mid-write gives
#     a torn copy and makes 7z exit with a warning. These are pure
#     runtime state, never source.
#   - COMPILED ARTIFACTS (*.+x Linux binaries, *.exe Windows binaries,
#     *.o/*.a) — every one is regenerated by the house build_*.sh /
#     build.ps1 scripts; ~85 MB combined, never source. Vendored *.dll
#     redistributables are KEPT (small, not built from house source).
#   - #.NNEST_ASSETS/ — ~228 MB of VENDORED third-party asset packs
#     (mineclonia mob/item textures, cdda-tilesets/UltimateCataclysm).
#     Not house source, not in git, re-fetchable from their upstream
#     projects. Keep one separate full copy of this dir if you care
#     about the exact snapshot; the house .7z is for house source.
#   - *.mp3 — all 11 are tracked in git (GitHub has them); the two big
#     #.ref reference tracks are ~15 MB of the old archive.
#   (Added 2026-09-08 — the #.NNEST_ASSETS + *.exe + *.mp3 exclusions,
#    plus -mx=5, drop the archive ~60 MB -> ~29 MB. In-house image
#    assets — the ~321 PNGs OUTSIDE #.NNEST_ASSETS — and all *.csv
#    sprite data are KEPT.)
# Deletes the previous house .7z so only the newest is kept.
set -e
cd "$(dirname "$0")"
SRC="x0.parent-level-dev-env-04.04"
OUT="${SRC}_$(date +%Y%m%d-%H%M%S).7z"

rm -f ${SRC}_*.7z

7z a -mx=5 "$OUT" "$SRC" \
    -xr'!.git' \
    -xr'!#.NNEST_ASSETS' \
    -xr'!*.+x' -xr'!*.exe' -xr'!*.o' -xr'!*.a' -xr'!*.so' \
    -xr'!*.mp3' \
    -xr'!*.raw' -xr'!*.rgba32' \
    -xr'!ascii_frames' \
    -xr'!*.log' -xr'!*frame_history.txt' -xr'!gl_cli_out.txt' \
    -xr'!node_modules' \
    -xr'!history.txt' \
    -xr'!entity_menu_history' -xr'!entity_menu_frame_*.txt' \
    -xr'!strip_history.txt' -xr'!strip_ascii_pulse.txt' -xr'!strip_frame_changed.txt' \
    -xr'!*.pulse.txt' -xr'!renderer_pulse.txt' -xr'!*_changed.txt' \
    -xr'!*_ledger.txt' -xr'!pending_tx.txt' \
    -xr'!*.seq' \
    -xr'!*.frame.txt'
echo "OK $OUT"
