#!/usr/bin/env python3
"""bookmark_badge_contrast_fix_harness.py - real, runnable example of
presentation_harness.py's reuse pattern (2026-08-25 direct instruction).

Reproduces presentations/bookmark-badge-contrast-fix/ END TO END: launches
cursword's real bookmarks window, drives it via the real relay/history
file (no mouse), dumps a real frame, crops the badge for a close-up, and
calls Harness.build_video() - no manual ffmpeg/relay wrangling by a human
or by Claude directly. Run it, then inspect the output video same as any
other presentation.

Usage (from anywhere, house_root is auto-detected relative to this file):
    python3 bookmark_badge_contrast_fix_harness.py
"""
import subprocess
import sys
import time
from pathlib import Path

from PIL import Image
from presentation_harness import Harness

# this file lives at .../pals/cursword/harnesses/ - house_root is 6
# levels up (harnesses -> cursword -> pals -> livedesk -> home -> uuid -> users -> xyzfs -> 44.xyz...)
# resolved by walking up to the real "44.xyz" house dir, not a fixed
# relative count, since exact nesting depth is easy to miscount by hand.
def find_house_root(start: Path) -> Path:
    d = start
    while d != d.parent:
        if d.name.startswith("44.xyz"):
            return d
        d = d.parent
    raise RuntimeError("could not find the house root (a '44.xyz*' directory) above " + str(start))


HOUSE_ROOT = find_house_root(Path(__file__).resolve())
PAL_DIR = HOUSE_ROOT / "xyzfs/users/0a9558a7-7c74-4358-833c-2d5b21edc421/home/livedesk/pals/cursword"
RELAY = HOUSE_ROOT / "#.desktop/db_hq_history.txt"
DUMP_PNG = Path("/tmp/db-hq-frame.png")

PROC_PATTERN = r"khtpm_core_render\.\+x.*bookmarks\.chtpm"
MGR_PATTERN = r"bookmarks_manager\.\+x.*cursword"


def launch_bookmarks():
    script = HOUSE_ROOT / "&.widgits/bookmarks/bm_menu.sh"
    with open("/tmp/bm-harness-launch.log", "w") as log:
        subprocess.Popen(
            ["setsid", "sh", str(script), str(HOUSE_ROOT), str(PAL_DIR)],
            stdout=log, stderr=log, stdin=subprocess.DEVNULL,
            start_new_session=True,
        )
    time.sleep(1.5)


def main():
    h = Harness(HOUSE_ROOT, feature_name="bookmark-badge-contrast-fix-via-harness")

    h.assert_zero_stray_processes(PROC_PATTERN)
    h.assert_zero_stray_processes(MGR_PATTERN)

    launch_bookmarks()
    shell_pids = h.stray_pids(PROC_PATTERN)
    mgr_pids = h.stray_pids(MGR_PATTERN)
    if len(shell_pids) != 1 or len(mgr_pids) != 1:
        raise RuntimeError(f"expected exactly 1 shell + 1 manager, got shell={shell_pids} mgr={mgr_pids}")

    try:
        # Frame 1: full window, row 1 focused by default
        frame1 = h.dump_frame(RELAY, DUMP_PNG)
        full_snap = Path("/tmp/harness_bm_full.png")
        full_snap.write_bytes(frame1.read_bytes())
        h.add_frame(
            full_snap, min_seconds=6,
            caption="Cursword's real bookmarks window, live - two real bookmarks, row 1 focused (the [>]1. badge).",
        )
        h.add_frame(
            full_snap, min_seconds=6,
            caption="The bug: the focused badge was hardcoded orange (#ff8c00), rendered directly on the row's own gold background (#d9b64a) - almost unreadable.",
        )

        # Frame 2: zoomed badge crop, proving the fix (this harness run
        # uses whatever binary is CURRENTLY built - if the fix is in
        # place, the badge will be dark brownish-red, not orange)
        im = Image.open(frame1)
        crop = im.crop((0, 135, 120, 160)).resize((720, 150))
        crop_path = Path("/tmp/harness_bm_badge_zoom.png")
        crop.save(crop_path)
        h.add_frame(
            crop_path, min_seconds=7,
            caption="Zoomed crop of the badge. badge_focus_color() in khtpm_draw_core.c picks a dark contrasting color instead of orange when the row's own background is light.",
        )
        h.add_frame(
            crop_path, min_seconds=6,
            caption="This frame was captured by a REUSABLE harness (presentation_harness.py) - not hand-run relay commands - proving the harness itself works end to end.",
        )
    finally:
        # clean shutdown via the window's own real Close row, then a
        # hard kill fallback - never leave stray processes behind
        h.send_ascii(RELAY, ord("5"))
        time.sleep(0.5)
        h.send_enter(RELAY)
        time.sleep(1)
        remaining = h.stray_pids(PROC_PATTERN) + h.stray_pids(MGR_PATTERN)
        if remaining:
            h.kill(remaining)
        still_there = h.stray_pids(PROC_PATTERN) + h.stray_pids(MGR_PATTERN)
        if still_there:
            print(f"WARNING: processes still alive after cleanup: {still_there}", file=sys.stderr)

    h.write_reproduce(
        "# Reproduce (via harness)\n\n"
        "This presentation was generated by "
        "`bookmark_badge_contrast_fix_harness.py` in cursword/harnesses/ - "
        "run it directly:\n\n"
        "```sh\n"
        "python3 cursword/harnesses/bookmark_badge_contrast_fix_harness.py\n"
        "```\n\n"
        "It launches cursword's real bookmarks window, drives it via the "
        "real relay/history file, dumps a real frame, crops the badge, "
        "and calls presentation_harness.py's Harness.build_video() - no "
        "manual steps. See presentation_harness.py's own docstring for "
        "the reusable primitives available to any future feature harness.\n"
    )
    out = h.build_video()
    print(f"\nharness complete: {out}")


if __name__ == "__main__":
    main()
