#!/bin/sh
# palettes_menu.sh - palette CATEGORY windows (v2, 2026-08-24)
# ============================================================
# REWORKED after direct correction: the toolbar HQ dropdown lists the
# categories directly (PDL rows hq_menu_10+ in #.desktop/livedesk_taskbar.pdl);
# each option opens ITS OWN db-style window showing that category's tiles
# immediately - there is NO intermediate category-menu window.
#   palettes_menu.sh <house_root> <category>
# Real tiles today: emojis (starter grid) and elements (all 50 compounds
# from chemistry_tiles_expanded CSV). A tile click really places onto
# the desk via tile-picker's proven ops (tp_set_brush + tp_place_desktop,
# same chain scenarios/test_tile_desktop_place.sh proves). Categories
# whose picker isn't built yet open their design-doc section instead of
# lying dead - see #.ref/menu/palletes/pallette-design.txt.
# fo-menu-sys pitfall #26: interactive rows are <button>, never <item>.

set -eu

SELF_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
HOUSE_DEFAULT=$(CDPATH= cd -- "$SELF_DIR/../.." && pwd)
SELF="$SELF_DIR/palettes_menu.sh"
CSV="$HOUSE_DEFAULT/#.ref/menu/palletes/chemistry_tiles_expanded🏆.csv"
EMOJI_PALLET="$HOUSE_DEFAULT/#.ref/menu/palletes/emoji-pallet-00.00.txt"
DESIGN_DOC="$HOUSE_DEFAULT/#.ref/menu/palletes/pallette-design.txt"
TP_OPS="$HOUSE_DEFAULT/&.widgits/tile-picker/ops/+x"
STATE_DIR="$SELF_DIR/state"
DESK_DIR="$HOUSE_DEFAULT/#.desktop"
# emoji->sprite toolchain + cache (2026-08-24): the house's one real
# emoji-image mechanism ("x11 renders emojis ... we have a specific
# renderer for emojis") - pre-convert each pallet glyph to sprite.csv via
# the taskbar's own prebuilt pair, then the palette window blits them as
# PNG-rendered tiles (same pipeline as the toolbar's clock-face glyph).
SPRITE_ROOT="$SELF_DIR/sprites"
EMOJI_SPRITES="$SPRITE_ROOT/emoji"
for _d in "$HOUSE_DEFAULT"/*.monads/*.livedesk-taskbar/ops/+x; do
    [ -f "$_d/emoji_gen_atlas.+x" ] && EMOJI_TOOLS="$_d" && break
done

ensure_emoji_sprite() {  # ensure_emoji_sprite <glyph> <n> - csv cached per index
    _g="$1"; _n="$2"
    [ -n "${EMOJI_TOOLS:-}" ] || return 0
    _dir="$EMOJI_SPRITES/$(printf '%03d' "$_n")"
    [ -f "$_dir/sprite.csv" ] && return 0
    mkdir -p "$_dir"
    "$EMOJI_TOOLS/emoji_gen_atlas.+x" "$_g" "$_dir/atlas.png" >/dev/null 2>&1 || return 0
    "$EMOJI_TOOLS/emoji_xtract.+x" "$_dir/atlas.png" 0 64 "$_dir/sprite.csv" >/dev/null 2>&1 || true
}

log() { mkdir -p "$SELF_DIR/audit"; printf '%s %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >> "$SELF_DIR/audit/palettes.log"; }


place() {  # place <glyph> - real desk placement, tile-picker's own chain
    _g="$1"
    mkdir -p "$STATE_DIR" "$DESK_DIR/tiles"
    "$TP_OPS/tp_set_brush.+x" "$STATE_DIR" "$_g" >/dev/null 2>&1 || true
    "$TP_OPS/tp_place_desktop.+x" "$STATE_DIR" "$DESK_DIR" >/dev/null 2>&1 || true
    log "placed glyph $_g onto $DESK_DIR/tiles/"
}

css() {
    cat > "$SELF_DIR/palettes.css" << 'EOF'
/* palettes.css - generated by palettes_menu.sh; db-hq/stats-hq subset.
 * REAL FIX 2026-08-25 (Stage 2 palettes port, live report "still doesn't
 * have the dark theme?"): this was left as the OLD standalone binary's
 * light theme (#ececec/#fafafa) after retargeting at the merged binary -
 * a functional-parity oversight, not a deliberate choice. Now matches
 * db-hq/stats-hq's own real dark palette (#141414/#181818/#1c1c1c/#2a2a2a)
 * verbatim. #ffd700 tile gold is a deliberate accent, kept as-is. */
window { background-color: #141414; font-family: Ubuntu; font-size: 10px; }
.settings-block { background-color: #181818; border: 1px solid #2a2a2a; border-width: 1; }
.block-title { background-color: #1c1c1c; color: #cccccc; font-weight: bold;
  font-size: 9px; position: absolute; top: -8px; left: 10px; }
.pal-hint { color: #888888; font-size: 9px; }
/* matrix view (pallette-design.txt VIEW SPECS): tiles chunked into
   pal-grid-row flex rows by the composer; the renderer scrolls them
   and draws a real thumb on pal-thumbtrack. */
.pal-grid-row { display: flex; flex-direction: row; gap: 4px; height: 56px; }
.pal-tile { background-color: #d9b64a; color: #000000; font-weight: bold;
  width: 48px; height: 48px; font-size: 15px; padding: 4px; }
.pal-wide { width: auto; min-width: 120px; }
.pal-thumbtrack { background-color: #2a2a2a; }
.bm-btn { color: #cccccc; font-weight: bold; }
EOF
}

# emit_tiles_matrix <cols> <css_class> [sprite_root] - reads
# "emoji<TAB>label" lines from stdin, chunks them into
# <row class="pal-grid-row"> blocks of <cols> tiles each
# (pallette-design.txt VIEW SPECS). With sprite_root set, tile N carries
# sprite="<root>/<NNN>" when that csv exists - the renderer blits the
# real PNG-rendered emoji instead of the font glyph (which the house's
# default font cannot show in color anyway).
emit_tiles_matrix() {
    _cols="$1"; _cls="$2"; _sroot="${3:-}"
    awk -F'\t' -v cols="$_cols" -v cls="$_cls" -v self="$SELF" -v sroot="$_sroot" '
    function flushrow(   i, sp, csv) {
        if (n == 0) return;
        printf "    <row class=\"pal-grid-row\">\n";
        for (i = 1; i <= n; i++) {
            sp = "";
            if (sroot != "") {
                csv = sprintf("%s/%03d/sprite.csv", sroot, idx[i]);
                if (system("test -f \"" csv "\"") == 0)
                    sp = sprintf(" sprite=\"%s/%03d\"", sroot, idx[i]);
            }
            printf "      <button class=\"%s\" label=\"%s\"%s onClick=\"exec:%s place %s\"/>\n", cls, lbl[i], sp, self, em[i];
        }
        printf "    </row>\n";
        n = 0;
    }
    {
        sub(/\r$/, "");
        if ($1 == "") next;
        cnt++;
        n++; em[n] = $1; lbl[n] = $2; idx[n] = cnt;
        if (n == cols) flushrow();
    }
    END { flushrow() }'
}

compose_emojis() {
    printf '    <text class="pal-hint" label="Click an emoji to place it on the desk."/>\n'
    # pre-render every pallet glyph to its cached sprite.csv (no-op for
    # already-generated indices), then compose the matrix with sprite=
    # attrs - PNG-rendered tiles, not font glyphs.
    awk '{ gsub(/\r/, ""); if ($0 != "") print }' "$EMOJI_PALLET" | while IFS= read -r _g; do
        _c=$((_c + 1)); ensure_emoji_sprite "$_g" "$_c"
    done
    awk '{ gsub(/\r/, ""); if ($0 != "") print $0 "\t" $0 }' "$EMOJI_PALLET" | emit_tiles_matrix 10 pal-tile "$EMOJI_SPRITES"
}

compose_elements() {
    printf '    <text class="pal-hint" label="Chemicals+Compounds - click to place."/>\n'
    tail -n +2 "$CSV" | while IFS=, read -r emoji name formula _rest; do
        [ -n "$emoji" ] || continue
        [ -n "$formula" ] && printf '%s\t%s %s (%s)\n' "$emoji" "$emoji" "$name" "$formula" ||
                          printf '%s\t%s %s\n' "$emoji" "$emoji" "$name"
    done | emit_tiles_matrix 4 "pal-tile pal-wide"
}

compose_stub() {  # honest placeholder until this category's real picker lands
    printf '    <text class="pal-hint" label="Picker not built yet - design is in the doc below."/>\n'
    printf '    <button class="bm-btn" label="Open Design Doc" onClick="open:%s"/>\n' "$DESIGN_DOC"
}

title_for() {
    case "$1" in
        emojis)     printf 'palettes: Emojis' ;;
        elements)   printf 'palettes: Chemicals+Compounds' ;;
        user-pallet) printf 'palettes: My Pallet' ;;
        rmmv)       printf 'palettes: RPG Maker Tiles' ;;
        piececraft) printf 'palettes: Piececraft Blocks' ;;
        cdda)       printf 'palettes: CDDA Tiles' ;;
        df)         printf 'palettes: Dwarf Fortress' ;;
        kenney)     printf 'palettes: Kenney 3D' ;;
        paint)      printf 'palettes: Paint Colors' ;;
        generate)   printf 'palettes: Generate' ;;
        *)          return 1 ;;
    esac
}

compose_window() {  # compose_window <key>  (writes palettes-<key>.chtpm)
    _k="$1"
    _t=$(title_for "$_k")
    {
        # REAL FIX 2026-08-25 (Stage 2 migration off the deprecated
        # standalone khtpm_hq_render.c - au11-hq/TPMOS-COMPLIANCE-DEBT.md) -
        # "palettes" class drives khtpm_entity_menu_render.c's own
        # g_is_palettes dispatch branch.
        printf '<window class="database-window palettes">\n'
        printf '  <panel class="settings-block">\n'
        printf '    <title class="block-title" label="%s"/>\n' "$_t"
        case "$_k" in
            emojis)   compose_emojis ;;
            elements) compose_elements ;;
            *)        compose_stub ;;
        esac
        printf '  </panel>\n'
        printf '</window>\n'
    } > "$SELF_DIR/palettes-$_k.chtpm"
    # khtpm_hq_render derives the css path from argv[2] by swapping the
    # extension (palettes-<key>.chtpm -> palettes-<key>.css) - publish the
    # shared sheet under the exact name this window will load.
    cp -f "$SELF_DIR/palettes.css" "$SELF_DIR/palettes-$_k.css"
}

launch_cat() {  # launch_cat <house> <key>
    _h="$1"; _k="$2"
    css
    compose_window "$_k"
    _CHTPM="$SELF_DIR/palettes-$_k.chtpm"
    for p in /proc/[0-9]*; do
        [ "$p" = "/proc/$$" ] && continue
        _cl=$(cat "$p/cmdline" 2>/dev/null | tr '\0' ' ') || continue
        case "$_cl" in *"$_CHTPM"*) kill "${p#/proc/}" 2>/dev/null || true ;; esac
    done
    sleep 0.2
    # REAL FIX 2026-08-25 (Stage 2 migration - see the class="palettes"
    # comment above) - the shared merged binary, not the deprecated
    # standalone khtpm_hq_render.c.
    BIN=$(echo "$_h"/*.monads/*.livedesk-taskbar/ops/+x/khtpm_entity_menu_render.+x)
    [ -x "$BIN" ] || { echo "palettes: renderer missing: $BIN" >&2; exit 1; }
    log "category window launched: $_k"
    exec "$BIN" "$_h" "$_CHTPM"
}

list_cats() {
    grep '^CATEGORY' "$SELF_DIR/pallets.pdl" | while IFS='|' read -r _ k _rest; do
        k=$(printf '%s' "$k" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        [ -n "$k" ] && printf '%s\n' "$k"
    done
}

case "${1:-}" in
    place)   shift; place "$@"; exit 0 ;;
    list)    list_cats; exit 0 ;;
    compose) css; compose_window "${2:?usage: compose <category>}"; exit 0 ;;
esac

# Arg forms:
#   palettes_menu.sh <category>            (what the tb PDL rows use -
#                           house defaults to this script's own root)
#   palettes_menu.sh <house_root> <category>
HOUSE="$HOUSE_DEFAULT"
KEY="${1:-}"
if [ -n "$KEY" ] && ! title_for "$KEY" >/dev/null 2>&1; then
    HOUSE="$KEY"
    KEY="${2:-}"
fi
[ -n "$KEY" ] || { echo "usage: palettes_menu.sh [<house_root>] <category>" >&2; exit 1; }
launch_cat "$HOUSE" "$KEY"
