#!/bin/bash
# play_event.sh — COMPATIBILITY SHIM, 2026-08-29 ("mr was just one
# project using events (probably the first) but it doesn't own events").
#
# The real play_event.sh moved to &.widgits/events-hq/ops/play_event.sh
# (shared events-hq ops, since Play is used by every entity/project in
# the house, not just muchi-pet). This shim stays here because several
# real, already-existing per-entity data files hardcode this OLD path in
# their own "Play"/METHOD action lines (found live via grep, not
# regenerated by any C source - e.g. m8_redhorned's and m6_golddeity's
# objects.pdl, cursword's meta.pdl) - editing those by hand was out of
# scope for this move (same reasoning as leaving the old +x/ op binaries
# in place: harmless duplication beats hand-editing generated/legacy
# per-entity artifacts one by one). Forwards to the real script unchanged
# so there is exactly one place the actual play_event.sh logic lives -
# no drift risk between two copies.
exec sh "$(cd "$(dirname "$0")/../../../&.widgits/events-hq/ops" && pwd)/play_event.sh" "$@"
