/* plan_cells - W1 op. Materializes a chapter's cell plan from
 * canon/plan/<book>/<chapter>.plan into canon/work/<book>/<chapter>/cells/,
 * one pipe-delimited spec per cell, plus a chapter header file.
 *
 * Plan format (pdl):  chapter|id|title|book|gold_verses
 *                     cell|id|title|v_from|v_to|scene_a;scene_b|beat_text
 *
 * Deterministic, zero model calls, idempotent (workdir rebuilt each run).
 * Usage: plan_cells.+x <book> <chapter>
 * Env:   PRISC_PROJECT_ROOT (house convention) or CWD. */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#pragma GCC diagnostic ignored "-Wformat-truncation"

#define MAX_PATH 4096
#define PATH_BUF (MAX_PATH + 256)
#define MAX_LINE 65536

static char project_root[MAX_PATH] = ".";

static void resolve_root(void) {
    const char *env = getenv("PRISC_PROJECT_ROOT");
    if (env && env[0]) snprintf(project_root, sizeof(project_root), "%s", env);
}

static void mkdirp(const char *path) {
    char cmd[PATH_BUF * 2];
    snprintf(cmd, sizeof(cmd), "mkdir -p '%s'", path);
    int rc = system(cmd);
    (void)rc;
}

int main(int argc, char **argv) {
    resolve_root();
    if (argc < 3) { fprintf(stderr, "usage: plan_cells.+x <book> <chapter>\n"); return 1; }
    const char *book = argv[1], *chapter = argv[2];

    char plan_path[PATH_BUF];
    snprintf(plan_path, sizeof(plan_path), "%s/canon/plan/%s/%s.plan", project_root, book, chapter);

    char work_root[PATH_BUF], cells_dir[PATH_BUF], hdr_path[PATH_BUF];
    snprintf(work_root, sizeof(work_root), "%s/canon/work/%s/%s", project_root, book, chapter);
    snprintf(cells_dir, sizeof(cells_dir), "%s/cells", work_root);
    mkdirp(cells_dir);

    char cells_hdr[PATH_BUF];
    snprintf(cells_hdr, sizeof(cells_hdr), "%s/cells.manifest", work_root);
    FILE *mf = fopen(cells_hdr, "w");
    if (!mf) { fprintf(stderr, "cannot write %s\n", cells_hdr); return 1; }
    fprintf(mf, "# cells.manifest - generated by plan_cells\n");

    char hdr_path_buf[PATH_BUF];
    snprintf(hdr_path_buf, sizeof(hdr_path_buf), "%s/chapter.pdl", work_root);
    hdr_path[0] = '\0';

    FILE *f = fopen(plan_path, "r");
    if (!f) { fprintf(stderr, "plan not found: %s\n", plan_path); return 1; }

    int cell_count = 0, gold_verses = 0;
    char line[MAX_LINE];
    while (fgets(line, sizeof(line), f)) {
        if (line[0] == '#' || line[0] == '\n') continue;
        char *tok = line;
        char *p1 = strchr(tok, '|'); if (!p1) continue;
        char *p2 = strchr(p1 + 1, '|'); if (!p2) continue;
        char *p3 = strchr(p2 + 1, '|'); if (!p3) continue;
        char *p4 = strchr(p3 + 1, '|'); if (!p4) continue;
        *p1 = '\0'; *p2 = '\0'; *p3 = '\0';

        if (strcmp(tok, "chapter") == 0) {
            const char *cid = p1 + 1, *ctitle = p2 + 1;
            gold_verses = atoi(p4 + 1);
            *p4 = '\0';
            const char *cbook = p3 + 1;
            FILE *cf = fopen(hdr_path_buf, "w");
            if (cf) {
                fprintf(cf, "chapter|%s|%s|%s|gold_verses=%d\n", cid, ctitle, cbook, gold_verses);
                fclose(cf);
            }
            snprintf(hdr_path, sizeof(hdr_path), "%s", hdr_path_buf);
            continue;
        }

        if (strcmp(tok, "cell") != 0) continue;
        char *p5 = strchr(p4 + 1, '|'); if (!p5) continue;
        *p4 = '\0'; *p5 = '\0';
        const char *ctitle = p2 + 1, *vfrom = p3 + 1, *vto = p4 + 1;
        const char *scenes = p5 + 1;
        const char *beat = strchr(p5 + 1, '|'); if (!beat) continue;
        *((char *)beat) = '\0';
        beat++;

        cell_count++;
        char spec_path[PATH_BUF];
        snprintf(spec_path, sizeof(spec_path), "%s/cell_%02d.pdl", cells_dir, cell_count);
        FILE *sf = fopen(spec_path, "w");
        if (!sf) continue;
        fprintf(sf, "id|cell_%02d\n", cell_count);
        fprintf(sf, "title|%s\n", ctitle);
        fprintf(sf, "v_from|%s\n", vfrom);
        fprintf(sf, "v_to|%s\n", vto);
        fprintf(sf, "scenes|%s\n", scenes);
        fprintf(sf, "beat|%s\n", beat);
        fclose(sf);

        fprintf(mf, "cell_%02d|%s|%s..%s|%s\n", cell_count, ctitle, vfrom, vto, scenes);
    }
    fclose(f);

    fprintf(mf, "cells|%d\n", cell_count);
    fprintf(mf, "gold_verses|%d\n", gold_verses);
    fclose(mf);

    printf("plan_cells: %s/%s -> %d cells (gold verses=%d)\n", book, chapter, cell_count, gold_verses);
    if (cell_count == 0) { fprintf(stderr, "no cells materialized - check plan format\n"); return 1; }
    return 0;
}
